/**
 * SQLite schema definition for ATC FieldConnect.
 * A relational structure lets multiple systems, printers, consumables,
 * images and inquiries attach to a single client visit.
 */

export const DB_NAME = 'atc_fieldconnect';
export const DB_VERSION = 1;

export const SCHEMA_STATEMENTS: string[] = [
  `CREATE TABLE IF NOT EXISTS employee_profile (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    employee_name TEXT NOT NULL,
    employee_id TEXT NOT NULL,
    mobile_number TEXT,
    email TEXT,
    department TEXT,
    designation TEXT,
    branch TEXT,
    profile_image_path TEXT,
    manager_name TEXT,
    pin_enabled INTEGER DEFAULT 0,
    pin_hash TEXT,
    biometric_enabled INTEGER DEFAULT 0,
    created_at TEXT,
    updated_at TEXT
  );`,

  `CREATE TABLE IF NOT EXISTS client_visits (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    visit_number TEXT UNIQUE,
    employee_id TEXT,
    employee_name TEXT,
    visit_date TEXT,
    visit_time TEXT,
    visit_type TEXT,
    client_name TEXT,
    business_name TEXT,
    contact_person TEXT,
    designation TEXT,
    mobile_number TEXT,
    whatsapp_number TEXT,
    email_address TEXT,
    alternate_number TEXT,
    full_address TEXT,
    area TEXT,
    city TEXT,
    state TEXT,
    pin_code TEXT,
    landmark TEXT,
    website TEXT,
    client_category TEXT,
    latitude REAL,
    longitude REAL,
    location_accuracy REAL,
    location_time TEXT,
    existing_system_status TEXT,
    printer_status TEXT,
    inquiry_title TEXT,
    inquiry_description TEXT,
    client_requirement TEXT,
    expected_quantity TEXT,
    expected_timeline TEXT,
    urgency TEXT,
    budget_available INTEGER DEFAULT 0,
    budget_amount REAL,
    decision_maker TEXT,
    competitor_info TEXT,
    quotation_required INTEGER DEFAULT 0,
    demo_required INTEGER DEFAULT 0,
    technical_visit_required INTEGER DEFAULT 0,
    follow_up_required INTEGER DEFAULT 0,
    consumable_scope TEXT,
    printer_scope TEXT,
    software_scope TEXT,
    mobile_app_scope TEXT,
    web_app_scope TEXT,
    lead_rating TEXT,
    lead_score INTEGER DEFAULT 0,
    business_potential TEXT,
    probability INTEGER DEFAULT 0,
    estimated_business_value REAL,
    priority TEXT,
    expected_closure_date TEXT,
    management_attention INTEGER DEFAULT 0,
    follow_up_date TEXT,
    follow_up_time TEXT,
    follow_up_mode TEXT,
    meeting_summary TEXT,
    client_response TEXT,
    employee_observation TEXT,
    challenges_identified TEXT,
    recommended_solution TEXT,
    next_action TEXT,
    additional_comments TEXT,
    status TEXT DEFAULT 'draft',
    created_at TEXT,
    updated_at TEXT
  );`,

  `CREATE TABLE IF NOT EXISTS visit_images (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    visit_id INTEGER,
    image_path TEXT,
    image_type TEXT,
    is_primary INTEGER DEFAULT 0,
    caption TEXT,
    created_at TEXT,
    FOREIGN KEY (visit_id) REFERENCES client_visits(id) ON DELETE CASCADE
  );`,

  `CREATE TABLE IF NOT EXISTS existing_systems (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    visit_id INTEGER,
    system_name TEXT,
    vendor TEXT,
    system_type TEXT,
    platform TEXT,
    number_of_users TEXT,
    satisfaction_level TEXT,
    issues TEXT,
    missing_features TEXT,
    renewal_date TEXT,
    support_provider TEXT,
    notes TEXT,
    FOREIGN KEY (visit_id) REFERENCES client_visits(id) ON DELETE CASCADE
  );`,

  `CREATE TABLE IF NOT EXISTS printer_details (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    visit_id INTEGER,
    printer_type TEXT,
    brand TEXT,
    model TEXT,
    quantity INTEGER DEFAULT 1,
    condition TEXT,
    consumables_used TEXT,
    monthly_usage TEXT,
    replacement_required INTEGER DEFAULT 0,
    service_required INTEGER DEFAULT 0,
    amc_opportunity INTEGER DEFAULT 0,
    image_path TEXT,
    remarks TEXT,
    FOREIGN KEY (visit_id) REFERENCES client_visits(id) ON DELETE CASCADE
  );`,

  `CREATE TABLE IF NOT EXISTS inquiry_categories (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    visit_id INTEGER,
    category_name TEXT,
    FOREIGN KEY (visit_id) REFERENCES client_visits(id) ON DELETE CASCADE
  );`,

  `CREATE TABLE IF NOT EXISTS consumable_opportunities (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    visit_id INTEGER,
    opportunity_status TEXT,
    consumable_type TEXT,
    brand TEXT,
    model TEXT,
    monthly_consumption TEXT,
    current_supplier TEXT,
    current_price TEXT,
    expected_date TEXT,
    remarks TEXT,
    FOREIGN KEY (visit_id) REFERENCES client_visits(id) ON DELETE CASCADE
  );`,

  `CREATE TABLE IF NOT EXISTS printer_opportunities (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    visit_id INTEGER,
    opportunity_status TEXT,
    required_printer_type TEXT,
    preferred_brand TEXT,
    quantity INTEGER DEFAULT 1,
    budget TEXT,
    expected_purchase_date TEXT,
    usage_requirement TEXT,
    remarks TEXT,
    FOREIGN KEY (visit_id) REFERENCES client_visits(id) ON DELETE CASCADE
  );`,

  `CREATE TABLE IF NOT EXISTS software_opportunities (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    visit_id INTEGER,
    opportunity_status TEXT,
    application_type TEXT,
    required_modules TEXT,
    current_problem TEXT,
    number_of_users TEXT,
    platform TEXT,
    integration_required TEXT,
    expected_timeline TEXT,
    budget TEXT,
    notes TEXT,
    FOREIGN KEY (visit_id) REFERENCES client_visits(id) ON DELETE CASCADE
  );`,

  `CREATE TABLE IF NOT EXISTS mobile_app_opportunities (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    visit_id INTEGER,
    opportunity_status TEXT,
    application_type TEXT,
    main_features TEXT,
    expected_users TEXT,
    integrations TEXT,
    timeline TEXT,
    budget TEXT,
    notes TEXT,
    FOREIGN KEY (visit_id) REFERENCES client_visits(id) ON DELETE CASCADE
  );`,

  `CREATE TABLE IF NOT EXISTS follow_ups (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    visit_id INTEGER,
    follow_up_date TEXT,
    follow_up_time TEXT,
    follow_up_mode TEXT,
    follow_up_purpose TEXT,
    assigned_employee TEXT,
    reminder_note TEXT,
    status TEXT DEFAULT 'pending',
    FOREIGN KEY (visit_id) REFERENCES client_visits(id) ON DELETE CASCADE
  );`,

  `CREATE INDEX IF NOT EXISTS idx_visits_date ON client_visits(visit_date);`,
  `CREATE INDEX IF NOT EXISTS idx_visits_status ON client_visits(status);`,
  `CREATE INDEX IF NOT EXISTS idx_images_visit ON visit_images(visit_id);`,
];
